### ISSUE TITLE
Callbacks section missing information

### ISSUE THREAD

**Issue by raulsebastianmihaila** [benschwarz/developers.whatwg.org#100]
Hello,

It seems to me that the Callbacks section is unfinished.

https://developers.whatwg.org/urls.html#callbacks

It says: "The following callback function type is used in various APIs that interact with File objects:", but nothing follows after the colon.

**Comment by benschwarz** [comment]
Covered by the source material, not this repo.

**Comment by domenic** [comment]
Source is at https://github.com/whatwg/html with the latest output being visible at https://html.spec.whatwg.org/multipage/; if the errors still are present there feel free to file a bug of pull request!
