### ISSUE TITLE
When cloning nodes from a template tag should we use cloneNode or importNode?

### ISSUE THREAD

**Issue by cganterh** [benschwarz/developers.whatwg.org#101]
In the [notes](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode#Notes) of mdn's `cloneNode` description it says:

>   To clone a node for appending to a different document, use Document.importNode() instead.

But in the example from <http://developers.whatwg.org> you use `cloneNode`.
Is this an error?

**Comment by benschwarz** [comment]
Covered by the source material, not this repo.

**Comment by domenic** [comment]
Source is at https://github.com/whatwg/html with the latest output being visible at https://html.spec.whatwg.org/multipage/; if the errors still are present there feel free to file a bug of pull request!
