### ISSUE TITLE
Clearer description of how https://developers.whatwg.org/ relates to the full spec

### ISSUE THREAD

**Issue by adrianh** [benschwarz/developers.whatwg.org#102]
On the https://developers.whatwg.org/ I'm told:

> Unlike the full HTML specification, this "web developer edition" removes information that only browser vendors need know.

and on https://developers.whatwg.org/introduction.html I'm told:

> The WHATWG work on HTML is all published in one specification parts of which are republished in an edition optimised for Web developers (which you are reading right now).

however, from a casual reading I'm not sure how current it is compared to the full spec. I'm currently asking myself things like:
- Is it an automatically updated document and always 100% up-to-date?
- Is it manually updated and missing some possibly relevant changes from the full spec?
- At the time of writing the full spec was last changed on 21 July 2015, and the developer edition github on March 9th. Does this mean the developer spec matches the full spec at the March 9th date? Does it mean that the changes after March 9th are irrelevant to the developer spec? Something else?
- Are they essentially two different related living specifications that evolve together at their own rates? 

Some kind of description of how the two specs relate to each other and, if relevant, links to the places where you can see relevant changes in the full spec that (possibly) haven't made it to the dev spec would be nice.

**Comment by domenic** [comment]
We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback). It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

We have a tracking issue for adding some sort of introduction at https://github.com/whatwg/html/issues/2780. Your feedback here is invaluable for the introduction we'll put together there.

As you may have gathered from the blog post, one of the main things we've done recently is ensuring that the two specs are always in sync, and generated from the same source document. So going forward these issues should not be a problem. But, we should say so in the introduction we assemble!

BTW, your help putting together an introduction would be very much appreciated---either directly via a PR, or by suggesting text over in that issue.

All this considered, let me roll this issue up into https://github.com/whatwg/html/issues/2780.
