### ISSUE TITLE
Please make your JavaScript free

### ISSUE THREAD

**Issue by ketefoy** [benschwarz/developers.whatwg.org#103]
I could not use your site (*e.g.*, search box) because it requires running JavaScript code that is not free software. Since a nonfree program disrespects the user's freedom, I decided not to run it. See http://gnu.org/philosophy/javascript-trap.html for more information, and please make your JavaScript code free.

**Comment by benschwarz** [comment]
JavaScript is a foundation of the web. Sorry this doesn't align with your idealistic values, but we'll see no change here.

**Comment by ketefoy** [comment]
The web should be unknown and mysterious to its users, using them however it sees fit.
