### ISSUE TITLE
How can we keep this updated with the latest HTML Standard?

### ISSUE THREAD

**Issue by domenic** [benschwarz/developers.whatwg.org#104]
Hey @benschwarz,

As you may know we moved the HTML Standard to GitHub at https://github.com/whatwg/html. We'd love to keep developers.whatwg.org in sync with the spec more readily, and are happy to help in any way possible. According to @Hixie, the build process can spit out something vaguely developer-like, but support is incomplete. (It uses the `w-nodev` annotations in the source.)

What can we do to get developers.whatwg.org updated?

Alternately, if you think it's not going to be possible for a while, maybe we should add an "outdated" notice?

**Comment by benschwarz** [comment]
Hi!

>  if you think it's not going to be possible for a while, maybe we should add an "outdated" notice?

I've been thinking about this for a while now. I really hate that the spec is out of date, and while I'm not a regular user of it myself, I know that many others enjoy using it still — I'd _love_ to see if kept up to date! 

I'm not familiar with `w-nodev`, and I'm kind of unsure how far behind my knowledge is of how everything hangs together, and to be perfectly honest, the post-processing that this repo does is… creative… at best. 

To get things moving, we need a full single page specification (I guess `https://html.spec.whatwg.org` will be the target?), and a bit of nudging to get the suite running with it. 

There has been a call to change the tooling to node/js based tooling (#90), but I think that the priority should be set on shipping an update specification. 

- [] Update the suite to run against the latest single page edition
- [] Publish it to gh-pages
- [] Point DNS at github (@hixie)
- [] Update design, modernise front-end
- [] Investigate more modern tooling (python spec-splitter update, remove janky ruby, etc) OR, make moves to make the role of this repository to style and deploy the specification (rather than the insane processing etc that it does now).

**Comment by domenic** [comment]
OK, sounds good! Anything for us to do on that list? https://html.spec.whatwg.org is indeed the latest full single-page version.

**Comment by benschwarz** [comment]
It needs to be prioritised… but I'm sure I can find a couple of hours somewhere to see where we're at here.

**Comment by Hixie** [comment]
Wattsi outputs a full-page version that's a better starting point for this than the full spec itself. I think the build script just ignores it currently, but we could expose that for sure.

**Comment by benschwarz** [comment]
@hixie, let's run with that

**Comment by annevk** [comment]
@benschwarz would it be ideal if we just generated a zip and pinged a URL on developers.whatwg.org that would collect the new version?

**Comment by benschwarz** [comment]
@annevk Definitely agree on the /ping and build. The only asset required should be the single HTML, so given that we're using GZIP for the transport… zip is just an unnecessary overhead.

**Comment by annevk** [comment]
I see. Currently we're also generating a multipage-dev version as far as I can tell. Perhaps we should stop doing that then...

**Comment by benschwarz** [comment]
@annevk The multipage edition has TOC's throughout etc? Perhaps we *should* use that one? Then we could remove the whole spec splitter (in theory), and just minimally process the multipage dev.

**Comment by annevk** [comment]
Correct, it has all that stuff. It's essentially the same multipage is published now, except without the text you don't want.

We should probably also add some review guidelines to whatwg/html's TEAM.md to ensure the appropriate text gets omitted from the developer version. Not sure we've been doing a good job of that.

**Comment by annevk** [comment]
https://html5.org/temp/multipage-dev.zip hosts a copy of somewhat recent output. As far as I can tell we don't actually generate a developer single-page copy so this might be our only hope at this point unless I'm missing something.

**Comment by Hixie** [comment]
Yeah I turned off the single-page dev version since d.w.o only has multipage. Sorry, I was confused in my earlier comment here.

**Comment by annevk** [comment]
@benschwarz if something like the above zip works for you, @domenic and I will make sure we put that online somewhere and then ping your server (what URL? share via email?).

**Comment by annevk** [comment]
@benschwarz any thoughts? We'd like this version of the HTML Standard to stay maintained. If you don't have time for it would it be okay with you if someone else took over?

**Comment by foolip** [comment]
What's the status of this? In https://github.com/whatwg/html/issues/626 the option of translating this variant of the spec has come up, but IMHO we really need developer.whatwg.org to be a fully supported and automatically updated first.

**Comment by annevk** [comment]
@foolip see #107. It seems @CaseyLeask is trying to get this to work.

**Comment by CaseyLeask** [comment]
@foolip @annevk I'm getting there. Sorry it's taken so much time :-/
I'm currently using https://html5.org/temp/multipage-dev.zip for the updated version, which removes `spec-splitter.py` and all the processing that it did.

**Comment by foolip** [comment]
@CaseyLeask No worries, with all of the tooling changes I imagine it's a lot of work to get back in sync. Will follow along in #107.

**Comment by domenic** [comment]
Now that https://github.com/benschwarz/developers.whatwg.org/pull/107 is merged, what is needed here? @CaseyLeask is it time for us to hook up something that automatically pushes your scripts the multipage-dev.zip, instead of hosting a one-time snapshot at the temp html5.org URL?

**Comment by domenic** [comment]
We've finalized on an approach that integrates directly into the HTML build pipeline over in https://github.com/whatwg/html/commit/28b739e2d4b1a5b71d0a90c1dad7ff1a99bd7288, with the results live at https://html.spec.whatwg.org/dev/.

@benschwarz, with your permission, I'd like to start the process of moving the work in this repository over to whatwg/html. That would concretely mean:

- Making a commit to master that removes all the files here and replaces the readme with a pointer to whatwg/html.
- Triaging the issue list based on what's fixed or still broken in the new version
- Redirecting https://developers.whatwg.org/ to https://html.spec.whatwg.org/

**Comment by benschwarz** [comment]
@domenic Amazing! This all sounds good to me. Thanks so much for all your efforts on this.
