### ISSUE TITLE
Spelling and punctuation in this standard

### ISSUE THREAD

**Issue by benkasminbullock** [benschwarz/developers.whatwg.org#106]
https://developers.whatwg.org/introduction.html#introduction

> The WHATWG work on HTML is all published in one specification parts of which are republished in an edition optimised for Web developers (which you are reading right now).

doesn't make sense without a comma:

> The WHATWG work on HTML is all published in one specification, parts of which are republished in an edition optimised for Web developers (which you are reading right now).

#2 

> A first abortive attempt at extending HTML in 1995 known as HTML 3.0 then made way to a more pragmatic approach known as HTML 3.2, which was completed in 1997. 

is much easier to read with commas:

A first abortive attempt at extending HTML in 1995, known as HTML 3.0, then made way to a more pragmatic approach known as HTML 3.2, which was completed in 1997. 

https://developers.whatwg.org/infrastructure.html#infrastructure

> no language-specific tailoirings

should read

> no language-specific tailorings

I would have directly edited the content files but I cannot see where they're stored in this repository.

**Comment by benschwarz** [comment]
Covered in source. Not here.

**Comment by domenic** [comment]
Source is at https://github.com/whatwg/html with the latest output being visible at https://html.spec.whatwg.org/multipage/; if the errors still are present there feel free to file a bug of pull request!
