### ISSUE TITLE
Keyboard cancellation of search box

### ISSUE THREAD

**Issue by krisdages** [benschwarz/developers.whatwg.org#109]
I tried instinctively to `Esc` out of the search box after focusing it with `/`.  It brought up the autocomplete suggestion panel.  I could only close that panel by clicking with the mouse (as far as I could tell).

I don't know if this is possible, but if I was using the "caret browsing" feature to navigate the document, it would be great if cancelling from the search box when using the keyboard would return the caret to where it was when search was initiated.

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

However, the new version does not yet have the search that was present in the old one. As such, we have a tracking issue at https://github.com/whatwg/html/issues/2779. Let me close this issue, but we'll be sure to keep this issue in mind when implementing the search over in the new version.
