### ISSUE TITLE
hgroup element removed from HTML5 spec

### ISSUE THREAD

**Issue by jonnybmc** [benschwarz/developers.whatwg.org#110]
Just wish to highlight that the hgroup element has officially been removed from the HTML5 specification as of 16 April, 2013

**Comment by benschwarz** [comment]
Aware of this, but this project is stalled so ¯\(°_o)/¯ Will keep it open, for future

**Comment by jonnybmc** [comment]
👍

**Comment by domenic** [comment]
This issue appears to be based on a misconception. hgroup was removed from [the W3C fork of the HTML Standard](https://annevankesteren.nl/2016/01/film-at-11), but this project (and its [newly revamped version](https://blog.whatwg.org/developers-edition-comeback)) track the HTML Standard itself. hgroup is alive and well, both [in the main spec](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element) and [in the developer's edition](https://html.spec.whatwg.org/dev/sections.html#the-hgroup-element).
