### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by ddumitre7** [benschwarz/developers.whatwg.org#111]
Images are missing. For instance the image on this page:

https://developers.whatwg.org/the-map-element.html#image-map

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

In the new version, images are present and working. See for example: https://html.spec.whatwg.org/dev/image-maps.html#image-map. So let me close this issue.
