### ISSUE TITLE
Page layout has a huge left margin, multiple footers

### ISSUE THREAD

**Issue by pornel** [benschwarz/developers.whatwg.org#112]
https://developers.whatwg.org/embedded-content-1.html

![screen shot 2016-07-28 at 12 24 56](https://cloud.githubusercontent.com/assets/72159/17210970/528af352-54be-11e6-9f11-ae076363de16.png)

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version does not appear to have this problem: https://html.spec.whatwg.org/dev/embedded-content.html. So let me close this issue.
