### ISSUE TITLE
Many entities glyphs are unexpanded in 17.2

### ISSUE THREAD

**Issue by Artoria2e5** [benschwarz/developers.whatwg.org#113]
https://developers.whatwg.org/named-character-references.html#named-character-references:

``` HTML
<!-- (invalid entity with missing semicolon for legacy support only) --><tr id="entity-Abreve">
<td> <code title="">Abreve;</code> </td> <td> U+00102 </td> <td> <span title="" class="glyph">&amp;Abreve;</span> </td> </tr>
<tr id="entity-abreve">
<td> <code title="">abreve;</code> </td> <td> U+00103 </td> <td> <span title="" class="glyph">&amp;abreve;</span> </td> </tr>
<tr id="entity-ac">
<td> <code title="">ac;</code> </td> <td> U+0223E </td> <td> <span title="" class="glyph">&amp;ac;</span> </td> </tr>
```

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version has this fixed: https://html.spec.whatwg.org/dev/named-characters.html#named-character-references. So I'll go ahead and close this issue.
