### ISSUE TITLE
read the press release. link is broken

### ISSUE THREAD

**Issue by CyrilWork** [benschwarz/developers.whatwg.org#115]
read the press release. link is broken
at the bottom of this page 
https://developers.whatwg.org/

**Comment by domenic** [comment]
We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback). It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version does not have a press release link, at least for now. Adding some sort of introduction is tracked by https://github.com/whatwg/html/issues/2780; probably we will link to both the original press release, [via archive.org](http://web.archive.org/web/20150220020906/http://archive.germanforblack.com:80/articles/html5-for-web-developers#_=_), and the blog post announcing the revamp.

So, let me close this in favor of that tracking issue over on whatwg/html.
