### ISSUE TITLE
Sortable tables

### ISSUE THREAD

**Issue by sliekens** [benschwarz/developers.whatwg.org#116]
The document that describes HTML tables mentions a `sortable` attribute but no browsers seem to support sortable tables. Was the attribute removed from the spec?

**Comment by domenic** [comment]
Yes; it was removed in https://github.com/whatwg/html/commit/59b7e2466c2b7c5c408a4963b05b13fd808aa07a. Unfortunately this repository is a bit behind the spec it's tracking :(. We have plans to fix that, but they keep getting deprioritized... I should make time for that.

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version has indeed removed the sortable attribute, so let me close this issue.

**Comment by sliekens** [comment]
Impressive. Although I wish they could have kept sortable tables in the spec so that I don't have to write so much code to sort my tables.
