### ISSUE TITLE
Inconsistent styles at the bottom of the table

### ISSUE THREAD

**Issue by nimbupani** [benschwarz/developers.whatwg.org#29]
http://gyazo.com/fea1982e4bba692ff3e896cbd236e723.png at the bottom of http://developers.whatwg.org/section-index.html in all browsers.

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

Reviewing this in the new version at https://html.spec.whatwg.org/dev/indices.html#events-2, we see that this is actually working as intended. The footnote here is a note, not just text, and as such needs to have a different style, like the rest of the notes in the spec.
