### ISSUE TITLE
Need a way to trigger an update

### ISSUE THREAD

**Issue by Hixie** [benschwarz/developers.whatwg.org#3]
Once this is up and running, we'll need a CGI script or something that the main spec gen script can ping to trigger an update.

e.g. have http://developers.whatwg.org/do-update.cgi which, when accessed using POST, fetches the spec source again and regen the web dev edition.

**Comment by benschwarz** [comment]
Let's cover this with the release of the work done in #107

**Comment by domenic** [comment]
[Everything is now generated from the same data source and deployed at the same time, yay!](https://blog.whatwg.org/developers-edition-comeback)
