### ISSUE TITLE
Microdata link in TOC leads to http://developers.whatwg.org/links.html

### ISSUE THREAD

**Issue by foolip** [benschwarz/developers.whatwg.org#33]
I find this confusing, I was expecting to find information about Microdata. Now, it is on that page, at http://developers.whatwg.org/links.html#microdata, but it'd be better if the TOC could better match what it's linked to.

**Comment by domenic** [comment]
It looks like this issue is fixed in the [revamped developer's edition](https://blog.whatwg.org/developers-edition-comeback), so let me close it.
