### ISSUE TITLE
anchors do not have a named anchor on the same page

### ISSUE THREAD

**Issue by stevepiercy** [benschwarz/developers.whatwg.org#36]
http://developers.whatwg.org/number-state.html#represents

"The input element represents"

"input" has a named anchor on the same page, but "represents" does not.

**Comment by domenic** [comment]
I'm not sure I fully understand this issue. However, I think it is probably fixed in the [revamped version of the developer's edition](https://blog.whatwg.org/developers-edition-comeback). So, let me close this. I will be happy to reopen if I misunderstood.
