### ISSUE TITLE
keyCode 191 does not always equal /

### ISSUE THREAD

**Issue by Zegnat** [benschwarz/developers.whatwg.org#55]
On Windows XP with a Swedish keyboard the `'` gives `keyCode == 191`. The `/` is possitioned at Shift (`16`) + 7 (`55`). This might be a problem with other non-US American keyboards as well.

Would there be ay way to use JavaScript to change the string displayed in the search box with the character that matches the checked `keyCode`? I have not been able to find a solution but there are many better JavaScript develops hanging around here I asume.

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

However, the new version does not yet have the search that was present in the old one. As such, we have a tracking issue at https://github.com/whatwg/html/issues/2779. Let me close this issue, but we'll be sure to keep this issue in mind when implementing the search over in the new version.
