### ISSUE TITLE
Make table of contents more useful

### ISSUE THREAD

**Issue by silviapfeiffer** [benschwarz/developers.whatwg.org#59]
When I'm trying to find a section on the developers site about, e.g. a particular element in HTML such as <video>, it's impossible to find it in the table of contents unless I know where it fits. It should be possible to show a full table of content down to at least three or four levels through maybe clicking on the toc elements (some kind of expand button) or through an expand button on the full table to get all subsections.

**Comment by domenic** [comment]
We've recently [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback). It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.) And it's built directly from the whatwg/html repository.

As such, let me move this issue to https://github.com/whatwg/html/issues/2793, where we can work on it directly. Thanks for your feedback; we were going to do some work on our build tools to remove the nodes from the DOM entirely, but then I found this issue!
