### ISSUE TITLE
Maybe the ol element missing the type attribute in the index...

### ISSUE THREAD

**Issue by m32po** [benschwarz/developers.whatwg.org#60]
At the link http://developers.whatwg.org/section-index.html#index, the attributes of ***ol*** element are *globals*, *reversed*, *start*. And the *type* attribute?

**Comment by benschwarz** [comment]
Covered by the source material, not this repo.

**Comment by domenic** [comment]
Source is at https://github.com/whatwg/html with the latest output being visible at https://html.spec.whatwg.org/multipage/; if the errors still are present there feel free to file a bug of pull request!
