### ISSUE TITLE
condition for omitting alt-text violates HTML Living Standard

### ISSUE THREAD

**Issue by searchtree** [benschwarz/developers.whatwg.org#67]
This was a total fluke catch...

I noted a rule I was unaware of earlier today while reading the <a href="http://dev.w3.org/html5/alt-techniques/#hv">w3c.org  Editor's Draft of 'HTML5: Techniques for providing useful text alternatives,' July 2nd, 2012</a>, specifying that the `title` attribute must Not be used to provide either alternative text or a caption for an image. Doing so effectively hides such text from users employing keyboard only and touch devices, for example, which is stated to be a 'willful violation of the HTML Living Standard.'

In the 'Embedded Content' section, 'The Image Element,' 'Alt,' it is noted that - if alternative text must be omitted because it is unavailable, one of several conditions must be met - particularly, ensuring the `title` attribute is present with a non-empty value. See <a href=http://developers.whatwg.org/embedded-content-1.html#unknown-images>"Images whose contents are not known"</a>. One example given is a blind man who posts a picture unaware of what it represents - which is similarly relevant to the basis for the note in the draft.

Either way - I think it's awesome that so much consideration is put into all of the documentation and standards. Here I am worrying about alt's & SEO... I would have never stopped to think of an implication like this. Thank you :).

**Comment by domenic** [comment]
I'm having trouble deciphering exactly what the problem is with the source document. And, this is a very old issue, which may have been fixed in the meantime. (Check [revamped developer's edition](https://blog.whatwg.org/developers-edition-comeback) to be sure.)

So, let me close this. But, I am happy to reopen if we are still missing something.
