### ISSUE TITLE
IDL attribute definition

### ISSUE THREAD

**Issue by sinthiav** [benschwarz/developers.whatwg.org#68]
As a first-time reader of this document, I found the frequent references to IDL attributes and content attributes very confusing. I had never heard of IDL attributes before. I would suggest a clear definition of these terms and their differences with a link to http://dev.w3.org/2006/webapi/WebIDL would make this document much more readable and understandable. While http://developers.whatwg.org/introduction.html#audience states that familiarity with IDL is optional, I found it impossible to understand this document without at least a definition of IDL. I thought until today that IDL referred to Microsoft's COM-RPC bindings, so you can see why it confused me.

**Comment by benschwarz** [comment]
Covered by the source material, not this repo.
