### ISSUE TITLE
Link to JSON copy of character reference names broken

### ISSUE THREAD

**Issue by scottmacpherson** [benschwarz/developers.whatwg.org#74]
After the "Named character references" section in Chapter 10.2 (http://developers.whatwg.org/named-character-references.html), there is a link to http://developers.whatwg.org/entities.json. Selecting this link returns a 404 not found error.

**Comment by pjstirling** [comment]
I tried to give fixing this a go, but I got stuck with ruby dependencies. All that's really necessary is to change the link with href "entities.json" -> "https://html.spec.whatwg.org/multipage/entities.json"

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version has a working link: see https://html.spec.whatwg.org/dev/named-characters.html. So, let me close this.
