### ISSUE TITLE
Link to HTML Editing APIs broken

### ISSUE THREAD

**Issue by DGrady** [benschwarz/developers.whatwg.org#75]
In section 8.6.1, the link to the HTML Editing APIs is dead. Maybe point to https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html instead?

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version doesn't seem to have a dead link in https://html.spec.whatwg.org/dev/interaction.html#editing-apis. However, arguably that section should not be in the spec, as telling you what other spec defines these implementer-facing terms is not very relevant. Let me thus roll the action of removing them into our tracker issue of https://github.com/whatwg/html/issues/1488.
