### ISSUE TITLE
Bad Practice for Form Controls

### ISSUE THREAD

**Issue by srsgores** [benschwarz/developers.whatwg.org#81]
In [the forms section](http://developers.whatwg.org/forms.html#forms), you are using paragraph ``<p>`` tags for sectioning content.  [It's a bad practice](http://stackoverflow.com/questions/2094344/is-it-wrong-to-use-paragraph-tags-for-html-for-inputs), and it's unsemantic:

```
<p><label>Full name: <input name=fn> <small>Format: First Last</small></label></p>
<p><label>Age: <input name=age type=number min=0></label></p>
<p><label>Post code: <input name=pc> <small>Format: AB12 3CD</small></label></p>
```

It's like Wordpress, and it's bad practice.  Maybe try this instead?

```
<form action = "/">
		<fieldset>
			<legend>Shipping Information</legend>
			<label>Full name: <input name = fn>
				<small>Format: First Last</small>
			</label>
			<label>Age: <input name = age type = number min = 0></label>
			<label>Post code: <input name = pc>
				<small>Format: AB12 3CD</small>
			</label>
		</fieldset>
	</form>
```

**Comment by benschwarz** [comment]
This is covered by the source material, and not this repo.
