### ISSUE TITLE
Bread crumb navigation may not be directory tree / category tree.

### ISSUE THREAD

**Issue by heporap** [benschwarz/developers.whatwg.org#83]
Hi.

I think bread crumb navigation is not category tree, but is history tree.
So I recommend this sample code for each them.

If you accessed "Main &gt; Product &gt; Dishwashers &gt; FAQ/common &gt; Diswashers" again, 
the bread crum navigation / history tree might be: 
&lt;p&gt;
&lt;a href="/"&gt;Main&lt;/a&gt; &amp;gt;
&lt;a href="/product"&gt;Product&lt;/a&gt; &amp;gt;
&lt;a href="/product/dishwashers"&gt;Dishwashers&lt;/a&gt; &amp;gt;
&lt;a href="/faq/common"&gt;common&lt;/a&gt; &amp;gt;
&lt;a href="/product/dishwasers"&gt;Dishwashers&lt;/a&gt; &amp;gt;
&lt;/p&gt;

and category tree might be:
&lt;ol&gt;
&lt;li&gt;&lt;a href="/"&gt;Main&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/product"&gt;Product&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/product/dishwashers"&gt;Dishwashers&lt;/a&gt;&lt;/li&gt;
&lt;/ol&gt;

**Comment by domenic** [comment]
I think this is an issue with the content of the spec, which is better filed at https://github.com/whatwg/html/issues if still relevant. As such, let me close this, but feel free to report it over there if it's still an issue!
