### ISSUE TITLE
Open TOC by default

### ISSUE THREAD

**Issue by marchbox** [benschwarz/developers.whatwg.org#84]
I found that in 100% times when I come to a section page, I click on “In this section…” button first to find the element I need. Do you have data on how frequent has the button been used? If it’s high, it’ll be worth just opening it by default.

**Comment by benschwarz** [comment]
Should be opened by default

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

In the new version, the "mini TOC" in each page is indeed open all the time. We're wondering if it even is a good idea to allow it to be collapsed. If you have any feedback on that, please let us know over on the HTML Standard issue tracker: https://github.com/whatwg/html/issues
