### ISSUE TITLE
Table of contents missing some sections

### ISSUE THREAD

**Issue by izh1979** [benschwarz/developers.whatwg.org#86]
Hi.

There are some oddities in the table of content in web-developer's version of HTML5.

First, the TOC (Table Of Content) on the main page looks incomplete. For example, consider this:

8 User interaction
    8.7 Drag and drop

Where is the 8.1-8.6 sections?

Okay, I understand that the 8, 8.1-8.5 sectioins are in the same document. But it is not possible to navigate to desired section directly from the main page.

Also there are some probably bugs like this: consider section 4.7.2. The iframe element:
http://developers.whatwg.org/the-iframe-element.html#the-iframe-element
How to get there? First, there is no link there on the main page. Second, you may think, that the link is in the "mini-TOC" on the document in section 4.7. Embedded content:
http://developers.whatwg.org/embedded-content-1.html#embedded-content-1

No, it is not there. The only possible way to go to 4.7.2, is to open 4.7, scroll to the bottom of the page, and click the link "Up next". It is not very convenient to navigating in such a way from the main page. Also, it's hard to keep what pages you are already visited.

**Comment by domenic** [comment]
Hi Igor! Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version has a table of contents without gaps, and all sections are available directly, either from the TOC or the mini-TOCs. So, let me close this.
