### ISSUE TITLE
Improve navigation to parent section

### ISSUE THREAD

**Issue by izh1979** [benschwarz/developers.whatwg.org#87]
There is no link "Up" on the pages. So it's hard to get to the parent section.
Yes, there is the "Back" button in the browsers, but if you are navigating in some non-linear order, it would be hard to go directly there.

The only possible way is to go to the main page by clicking on "HTML: The Living Standard". But is is not underlined, nor highlighted (until you hover the mouse -- and on mobile devices it will not highlighted ever), so it's hard to find that it is a link.

I suggest to add the link "Up" to the end of the pages.

And, IMHO, it would be nice to make a red WHATWG image to be a link to whatwg.org.
It's strange that the whole site doesn't have a single link to whatwg.org (except the link
to full version of the HTML5 standard).

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version doesn't really have a notion of parent and child sections; there is only one level of splitting. Furthermore, it does contain a link to whatwg.org, as the logo on each page. So, I think this is fixed, and can be closed.
