### ISSUE TITLE
Missing "selectedness" section

### ISSUE THREAD

**Issue by garaden** [benschwarz/developers.whatwg.org#88]
One section (http://developers.whatwg.org/the-button-element.html#a-form-control%27s-value) mentions a "selectedness" section that isn't in this document. It's in the W3C's here: (http://www.w3.org/TR/html5/forms.html#concept-option-selectedness).

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

It looks like both the new and the old version suffer from this problem. However, to me it's a symptom of a larger problem, which is that the section you cite (now at https://html.spec.whatwg.org/dev/form-control-infrastructure.html#a-form-control%27s-value) is not very developer-friendly. Concepts like value, API value, checkedness, or selectedness are mostly for implementers. We should instead work to rewrite that section to explain the basic distinction for developers, without referencing those concepts.

As such, let me roll this into the general issue for tracking developer-facing vs. implementer-facing text, which is https://github.com/whatwg/html/issues/1488.
