### ISSUE TITLE
Rewrite the build system in Node.js

### ISSUE THREAD

**Issue by strugee** [benschwarz/developers.whatwg.org#90]
Currently, AFAICT, the build system is written in an arcane combination of Ruby and Python. According to GitHub there's also some PHP in there, although this seems to not be a part of the build system.

I propose rewriting the build system in Node.js (and specifically, [Gulp][1]). This will provide more consistency in the repository.

WRT to the choice of Node + Gulp, these are just my personal preferences. Using Node has the advantage that we're writing in a web language (JS). Gulp is poised to become the most popular Node build system, displacing Grunt, but it's really just a personal preference of mine.

I'm very interested in working on this, but as this is obviously a large project I'm filing this issue to solicit feedback before I invest a lot of time in it. (If the community decides to go with something besides Gulp, though, I may not be able to do this myself.)

 [1]: http://gulpjs.com/

**Comment by strugee** [comment]
> If you're looking for a holiday project, this could be it :smile:

It's on my list! :P

**Comment by Hixie** [comment]
The single page spec doesn't include the annotations for what shouldn't be included in the developers version, they're stripped during publication. The source file does. You could generate it from the source file, or I could generate an intermediate version from the source file, or I could generate the final version from the source file. I'm happy to do either of the above. If I'm to generate something, I just need a precise description of what it is I'm to generate.

**Comment by benschwarz** [comment]
@hixie Lets use the actual source file and modify this code to take out what we don't want.

**Comment by benschwarz** [comment]
We'll modernise the suite after #107 drops, until then. This is on ice.
