### ISSUE TITLE
default landing page's HTML markup has lots of sublists of empty list items

### ISSUE THREAD

**Issue by rockxloose** [benschwarz/developers.whatwg.org#91]
![x](https://cloud.githubusercontent.com/assets/1190159/5579002/2d41930a-9087-11e4-9af4-2facec94ea76.png)

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version does not seem to have this problem, so let me close this.
