### ISSUE TITLE
Provide Code/Examples for Browsing Contexts - Window - Document mapping

### ISSUE THREAD

**Issue by idthiru** [benschwarz/developers.whatwg.org#92]
Could you provide code/examples for the following in the <a href="https://developers.whatwg.org/browsers.html#browsing-context">browsing context</a> section? for the following scenarios?
"There are two exceptions. First, ...." and "Second,..."

Also could you provide examples to how a document <em>becomes part of</em> or <em>added</em> to the browsing context's <em>session history</em>?

thanks,
thiru

**Comment by strugee** [comment]
This repository doesn't deal with the content of the specification. It only deals with the styling. You'll have better luck contacting the upstream WHATWG people, who maintain the full technical specification.

**Comment by idthiru** [comment]
Could you tell how I can reach them?

thanks
-t

**Comment by strugee** [comment]
If you open up the full specification, it allows you to submit feedback inline.

**Comment by strugee** [comment]
That being said, your request will probably be rejected. Examples don't generally belong in technical specifications.

**Comment by domenic** [comment]
Source is at https://github.com/whatwg/html with the latest output being visible at https://html.spec.whatwg.org/multipage/; we'd welcome a bug report about this, although maybe it is clearer in the full output.
