### ISSUE TITLE
Statements are Conflicting

### ISSUE THREAD

**Issue by idthiru** [benschwarz/developers.whatwg.org#94]
Following statements about the &lt;body&gt; are conflicting. 

"Thus, for example, a bubbling error event dispatched on a child of the body element of a Document would **first** trigger the onerror event handler content attributes **of that element**, **then** that of the **root html element**, and **only then** would it trigger the onerror event handler content attribute **on the body element**. This is because the event would bubble *from* the *target*, to the **body**, to the **html**, to the Document, to the Window"

Shouldn't the order be the **target element** *then* its **root HTML** and *then* to the **body**?

**Comment by strugee** [comment]
This issue doesn't belong here. Use the feedback tool of the full specification to submit this to the WHATWG.
