### ISSUE TITLE
Can you Make the Hyperlink Open in a New Tab?

### ISSUE THREAD

**Issue by idthiru** [benschwarz/developers.whatwg.org#96]
The footer in every page (I believe) has a link to the issues page in github. Can you make the link so that clicking on it opens the issues page in a new tab?

"please [raise an issue](https://github.com/benschwarz/developers.whatwg.org/issues)"

**Comment by strugee** [comment]
-1 from me, mostly because if you really want to open in a new tab, you can just Ctrl-click, but if you want to do the opposite, it isn't nearly as convenient.

But of course, @benschwarz gets the final call.

**Comment by benschwarz** [comment]
Generally I'm pretty against doing that because it relinquishes control for people—the benefits are generally unquantifiable too.

I understand the use case of filing an issue, but people seem to manage just fine already. 

Sorry to close, but that's just generally my thinking
